name: MineBroadcast
main: dev.truewinter.minebroadcast.MineBroadcast
version: ${project.version}
author: TrueWinter
description: Send messages to staff when players mine blocks. This is a fork of bendem's OreBroadcast
api-version: 1.18

commands:
    mb:
        usage: |
            MineBroadcast command. Type '/mb help' for more informations
        description: MineBroadcast commands

permissions:
    mb.*:
        description: Give access to all MineBroadcast functionalities
        default: op
        children:
            mb.commands.*: true
            mb.broadcast: true
            mb.receive: true
    mb.commands.*:
        description: Give access to all the plugin commands
        default: op
        children:
            mb.commands.reload: true
            mb.commands.clear: true
    mb.commands.reload:
        description: Players with this permission can reload the config
        default: op
    mb.commands.clear:
        description: Players with this permission can clear the blacklist
        default: op
    mb.commands.optout:
        description: Players with this permission can opt out from the plugin broadcasts
        default: op
    mb.commands.optin:
        description: Players with this permission can opt in to the plugin broadcasts
        default: op
    mb.commands.statistics:
        description: Get mining statistics for a player
        default: op
    mb.commands.startstats:
        description: Starts the StatisticsSaver for a player. Use the StatisticsSaver only when needed.
        default: op
    mb.commands.stopstats:
        description: Stops the StatisticsSaver for a player
        default: op
    mb.commands.resetplayer:
        description: Resets PlayerMiningStatistics/MiningMonitor for this player
        default: op
    mb.broadcast:
        description: Players with this permission will send messages when they mine blocks.
        default: true
    mb.receive:
        description: Players with this permission will receive MineBroadcast messages.
        default: op
